language: php

services:
  - mysql

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: WP_VERSION=5.4
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - nvm install 10

before_script:
  - composer install
  - npm install
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

script:
  - composer build
  - composer lint-all
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer test
    fi

notifications:
  email: false
