language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install
  - npm install

script:
  - composer build
  - composer lint-all

notifications:
  email: false
