language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - nvm install 10

before_script:
  - composer install
  - npm i -g npm@latest
  - npm install

script:
  - composer build
  - composer lint-all

notifications:
  email: false
