name: Plugin check
on:
  push:
    branches: [ 'stable', 'release/*' ]
  pull_request:
    branches: [ 'stable' ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install
        run: |
          composer install --no-interaction
          npm ci --ignore-scripts

      - name: Build
        run: |
          composer build
          npm run build

      - name: Package plugin
        run: |
          mkdir -p ./dist
          rsync -rc --exclude-from=.distignore ./ ./dist/statify --delete --delete-excluded

      - name: Check WP plugin
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: ./dist/statify
