name: Plugin asset/readme update
on:
  push:
    branches:
      - stable
jobs:
  stable:
    name: Push to stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install
        run: |
          composer install --no-interaction
          npm ci --ignore-scripts
      - name: Build
        run: |
          composer build
          npm run build
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          README_NAME: readme.txt
